### ISSUE TITLE
error executing  :  'node index.js'

### ISSUE THREAD

**Issue by satyamsah** [airavata-courses/madrinathapa#4]
Hi,
 Could you please check,it did not work after executing node index.js:

module.js:472
    throw err;
    ^

Error: Cannot find module 'seneca-web-adapter-express'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntuaws/myvirtualenv/madrinathapa/Assignment1/Services/hello-world/index.js:9:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

And also could you please change your commands to --save.

**Comment by madrinathapa** [comment]
Hello Satyam,

I'm so sorry. I forgot to mention this one. Could you please first install,
npm install seneca-web-adapter-express --save and then run the file.

P.s. I will update the README.md ASAP. Thank you for pointing it out.

Thank you,
Madrina Thapa

**Comment by satyamsah** [comment]
Sorry to bug you, but I would suggest you to execute your steps from scratch on clean env.
If everything works fine, kindly let me know

**Comment by satyamsah** [comment]
Hi Could you please help me in getting .NET core for ubuntu.
